// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcEour3E4ehIafFa6Go3tacoZpPvGdeg',
    appId: '1:521551501703:web:7c2a34982b2d54b623db22',
    messagingSenderId: '521551501703',
    projectId: 'sesac-workout-tracker',
    authDomain: 'sesac-workout-tracker.firebaseapp.com',
    storageBucket: 'sesac-workout-tracker.firebasestorage.app',
    measurementId: 'G-WGTLNGPGVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3S-iTreWZjNmlVAh7DeOxS6OUCZNtQ80',
    appId: '1:521551501703:android:cc946d3e980b7dcb23db22',
    messagingSenderId: '521551501703',
    projectId: 'sesac-workout-tracker',
    storageBucket: 'sesac-workout-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSXzirXtpawZiiWaO50LHJ91yUxuJgeA',
    appId: '1:521551501703:ios:123f992317ea8ca023db22',
    messagingSenderId: '521551501703',
    projectId: 'sesac-workout-tracker',
    storageBucket: 'sesac-workout-tracker.firebasestorage.app',
    iosBundleId: 'com.neonsigntrap.workoutTracker2026',
  );
}
